### ISSUE TITLE
check hardware possibilites

### ISSUE THREAD

**Issue by srieger1** [srieger1/digsinet#13]
https://www.ebay.com/itm/125970047180?itmmeta=01HQTMMWZ0WFKEQ2Q3BTJXRNQS&hash=item1d546660cc:g:ClkAAOSw07Vkg0r-&itmprp=enc%3AAQAIAAAA4D0mBNI3L74GIlmzSsVQLZIBXg%2F83j3nIb5FSs0VeN4sU3qkOn4ET7w5nrU0UoNkufkbAw1pHM8vZPn%2FlLf%2BrsLLaxVwEIrYWZmNHIJgH7b1lEVbOPbuwE%2FMbNrD1yC7k2o0PD34MubljytUEkFrOQs4BRbNfDDKCWZJn0XNZwQyZ98RkFUYfeu%2FgCn9Us0bOGFpOeq2QoxaBbhqquTe4xA24joPcIwmsLwbH--G2n0b%2Fok8EsSteupl1MdeutdaUMTAieLxl0ksNNnAIelxmGQ%2B5tJ4%2BHFsZg4pEAm1Sjq2%7Ctkp%3ABFBMyM_T1L5j

or maybe

https://www.fs.com/products/119649.html

**Comment by Shochraos** [comment]
@srieger1 and me have decided on the hardware that we're going to use. 

We're going to be using two Bluefield-2 SoC-Based Smart-NICs, as they provide a lot of useful features for our project such as NFV, Firewall, IDS and OVS Control Plane. Fortunately the buyer who sold those NICs answered and we were able to buy them. 

Furthermore, we decided that we were going to buy two ASIC-Based Smart-NICs as well, specifically the NVIDIA Connect-X 5/6 depending on availability. 
One thing to note: The Connect-X 5 are offically marked as End-Of-Life by NVIDIA, so using them might pose some difficulties but it's (probably) nothing too major and I'll be able to figure it out.
