### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Lachstec** [srieger1/digsinet#18]
Some form of Documentation would be useful to help onboarding new contributors. Maybe Pdoc deployed to Github Pages?

- Inline Documentation with Pdoc
- Update README.md

**Comment by srieger1** [comment]
Thanks to @Lachstec initial version of the documentation is now avaiable as github page and now also referenced as about at the top of the repo

**Comment by Lachstec** [comment]
The docs have been updated including information about the configuration and current limitations. I think this issue can be closed for now, as some major changes are planned, thus more documentation would be a bit wasted.

**Comment by srieger1** [comment]
@Lachstec absolutely! Thanks again for your work! I wanted to take a look into generating the static pages of the documentation directly in the GitHub action, but this can also be done later. I'll close the issue.
