### ISSUE TITLE
implement storage of gNMI data, ideally using real-time storage

### ISSUE THREAD

**Issue by srieger1** [srieger1/digsinet#3]

**Comment by srieger1** [comment]
@Sirulex: @Lachstec is currently working on improvements for the queues. If we move to real-time stream processing or queues, these might possibly also offer persistence and storage. Model state and events would than be consistently stored and processed in the queues or data streaming solution. Side note: this is also discussed as an open topic in the IRTF NMRG for Network Digital Twins. Maybe we should keep an eye on that.

**Comment by Lachstec** [comment]
I am currently looking at some vendors offering Real Time stream processing of events. The candidates are:

- RabbitMQ
- Celery
- Apache Kafka

Results and interesting things will be tracked in this issue.

**Comment by Lachstec** [comment]
Being worked on in #19
